name: Microservices CI/CD

on:
  push:
    branches:
      - main
      - develop

    tags:
      - 'v*'

  pull_request:
    branches:
      - main

jobs:

  build-test-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: |
          dotnet restore ./Gateway.Api/Gateway.Api.csproj
          dotnet restore ./Users.Api/Users.Api.csproj
          dotnet restore ./Orders.Api/Orders.Api.csproj
          dotnet restore ./Catalog.Api/Catalog.Api.csproj

      - name: Build projects
        run: |
          dotnet build ./Gateway.Api/Gateway.Api.csproj --no-restore
          dotnet build ./Users.Api/Users.Api.csproj --no-restore
          dotnet build ./Orders.Api/Orders.Api.csproj --no-restore
          dotnet build ./Catalog.Api/Catalog.Api.csproj --no-restore

      - name: Run tests
        run: dotnet test --no-build

      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # USERS API

      - name: Build Users API
        run: |
          docker build \
            -t juancamba/users.api:${{ steps.version.outputs.VERSION }} \
            -t juancamba/users.api:latest \
            ./Users.Api

      - name: Push Users API
        run: |
          docker push juancamba/users.api:${{ steps.version.outputs.VERSION }}
          docker push juancamba/users.api:latest

      # ORDERS API

      - name: Build Orders API
        run: |
          docker build \
            -t juancamba/orders.api:${{ steps.version.outputs.VERSION }} \
            -t juancamba/orders.api:latest \
            ./Orders.Api

      - name: Push Orders API
        run: |
          docker push juancamba/orders.api:${{ steps.version.outputs.VERSION }}
          docker push juancamba/orders.api:latest

      # CATALOG API

      - name: Build Catalog API
        run: |
          docker build \
            -t juancamba/catalog.api:${{ steps.version.outputs.VERSION }} \
            -t juancamba/catalog.api:latest \
            ./Catalog.Api

      - name: Push Catalog API
        run: |
          docker push juancamba/catalog.api:${{ steps.version.outputs.VERSION }}
          docker push juancamba/catalog.api:latest

      # GATEWAY API

      - name: Build Gateway API
        run: |
          docker build \
            -t juancamba/gateway.api:${{ steps.version.outputs.VERSION }} \
            -t juancamba/gateway.api:latest \
            ./Gateway.Api

      - name: Push Gateway API
        run: |
          docker push juancamba/gateway.api:${{ steps.version.outputs.VERSION }}
          docker push juancamba/gateway.api:latest